[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "clapi"
version = "1.0.0"
dependencies = [
    "requests==2.34.2",
    "python-dotenv==1.2.2"
]

[tool.setuptools]
py-modules = ["main", "config"]

[tool.setuptools.packages.find]
include = [
    "core*",
    "modules*",
    "utils*"
]

[project.scripts]
clapi = "main:main"
